---
# tasks file for 1c_ls

#- name: Install required packages
- include: "install-{{ ansible_os_family }}.yml"

- name: Copy zabbix userparameter files for license server
  copy:
    src: '{{ item }}'
    dest: '{{ zabbix_configs }}'
    owner: root
    group: root
    mode: 0644
  with_items:
    - userparameter_1c-ls.conf
    - userparameter_1c-lf.conf
  notify:
    - Add host to group for restart zabbix agent

- name: Copy scripts for license server
  copy:
    src: '{{ item }}'
    dest: /var/lib/zabbix/scripts/
    owner: zabbix
    group: zabbix
    mode: 0755
  with_items:
    - 1c_license_server.sh
    - 1c_license_files.sh