---
# tasks file for 1c_ws

#- name: Install required packages
- include: "install-{{ ansible_os_family }}.yml"

- name: Copy zabbix userparameter files for work server
  copy:
    src: '{{ item }}'
    dest: '{{ zabbix_configs }}'
    owner: root
    group: root
    mode: 0644
  with_items:
    - userparameter_1c-ws.conf
    - userparameter_1c-lf.conf
  notify:
    - Add host to group for restart zabbix agent

- name: Copy scripts for work server
  copy:
    src: '{{ item }}'
    dest: /var/lib/zabbix/scripts/
    owner: zabbix
    group: zabbix
    mode: 0755
  with_items:
    - 1c_work_server.sh
    - 1c_license_files.sh

- name: Make directory for 1C tech log
  file:
    name: /var/log/1C
    owner: usr1cv8
    group: grp1cv8
    state: directory
    mode: 0750

- name: Make directory for 1C tech log
  file:
    name: /var/log/1C/zabbix
    owner: usr1cv8
    group: grp1cv8
    state: directory
    mode: 0750

- name: Make directory for problem log
  file:
    name: /var/log/1C/zabbix/problem_log
    owner: zabbix
    group: grp1cv8
    state: directory
    mode: 0750

- name: Attach zabbix user to 1C group
  user:
    name: zabbix
    groups: grp1cv8
    append: yes

