---
# tasks file for 1c_cs

- name: Copy sudoers file for zabbix user
  copy:
    src: zabbix.sudoers
    dest: /etc/sudoers.d/zabbix
    owner: root
    group: root
    mode: 0440

- name: Copy userparameter for central server
  copy:
    src: userparameter_1c-cs.conf
    dest: '{{ zabbix_configs }}'
    owner: root
    group: root
    mode: 0644
  notify:
    - Add host to group for restart zabbix agent


- name: Copy main script for central server
  copy:
    src: 1c_central_server.sh
    dest: /var/lib/zabbix/scripts/
    owner: zabbix
    group: zabbix
    mode: 0755
